### ISSUE TITLE
Configurable upload folder?

### ISSUE THREAD

**Issue by nanawel** [9001/party-up#4]
Hi,

Maybe it would be handy to be able to define a target folder for uploads, in order to keep the root folder a bit cleaner.
The folder would be created on-the-fly if needed.

**Comment by 9001** [comment]
Hey o/

I'm happy to say this is already possible! it's just not very intuitive :-)

When you're specifying the server url, you can add the folders you want at the end of the URL, for example https://yourbox.com/up/foo/bar/.

I'm not sure how this could be indicated in the UI; maybe changing the label of the config entry to "Server URL / Upload Path" would be enough? I recall it was really tricky to add help-text to the input prompts, which is a shame because that would have been great :p

**Comment by nanawel** [comment]
Ah right! I had this intuition but wasn't sure this was possible, and so I did not even test it.
That's perfect, thanks!
